name: Release

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: release
      run: |
        .github/scripts/release.sh > notes.txt

    - name: notes
      run: |
        {
          echo 'NOTES<<EOF'
          cat notes.txt
          echo EOF
        } >> "$GITHUB_ENV"

    - name: git
      run: |
        git config user.name "qlibs@github.com"
        git config user.email "noreply@github.com"

    - name: commit
      run: |
        if ! git diff --quiet; then
          git add qlibs
          git commit -m "release: $(date +'%Y_%m_%d')"
        fi

    - name: tag
      run: |
        TAG_NAME=qlibs.$(date +'%Y_%m_%d')
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: push
      run: git push origin main

    - name: github
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: ${{ env.TAG_NAME }}
        body: |
          <a href="https://qlibs.github.io"><img width="25%" src="https://qlibs.github.io/img/qlibs_logo.png" /></a>

          ## Libraries

          ${{ env.NOTES }}

          ## Integration

          > CMake/CPM?

            ```
            CPMAddPackage(
              Name qlibs
              GITHUB_REPOSITORY qlibs/qlibs
              GIT_TAG ${{ env.TAG_NAME }}
            )
            add_library(qlibs INTERFACE)
            target_include_directories(qlibs SYSTEM INTERFACE ${qlibs_SOURCE_DIR})
            add_library(qlibs::qlibs ALIAS qlibs)
            ```

            ```
            target_link_libraries(${PROJECT_NAME} qlibs::qlibs);
            ```
        draft: false
        prerelease: false
