name: Release

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: release
      run: |
        .github/scripts/release.sh > notes.txt || echo "Nothing to release" && exit 0

    - name: changes
      id: check-changes
      run: |
        if git diff --quiet; then
          echo "No changes to commit."
          echo "found_changes=false" >> $GITHUB_ENV
        else
          echo "found_changes=true" >> $GITHUB_ENV
        fi

    - name: notes
      if: env.found_changes == 'true'
      id: read_release_notes
      run: |
        echo "NOTES=$(cat notes.txt)" >> $GITHUB_ENV

    - name: git
      if: env.found_changes == 'true'
      run: |
        git config user.name "qlibs@github.com"
        git config user.email "noreply@github.com"

    - name: commit
      if: env.found_changes == 'true'
      run: |
        git add .
        git commit -m "Release $(date +'%Y_%m_%d')"

    - name: tag
      if: env.found_changes == 'true'
      id: tag_name
      run: |
        TAG_NAME=qlibs.$(date +'%Y_%m_%d')
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: push
      if: env.found_changes == 'true'
      run: git push origin main

    - name: github
      if: env.found_changes == 'true'
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: ${{ env.TAG_NAME }}
        body: |
          <a href="https://qlibs.github.io"><img style="width:50%" src="https://qlibs.github.io/img/qlibs_logo.png" /></a>

          ## Libraries

          ${{ env.NOTES }}

          ## FAQ

          - How to integrate with CMake/CPM?

            ```
            CPMAddPackage(
              Name qlibs
              GITHUB_REPOSITORY qlibs/qlibs
              GIT_TAG ${{ env.TAG_NAME }}
            )
            add_library(qlibs INTERFACE)
            target_include_directories(qlibs SYSTEM INTERFACE ${qlibs_SOURCE_DIR}) add_library(qlibs::qlibs ALIAS qlibs)
            ```

            ```
            target_link_libraries(${PROJECT_NAME} qlibs::qlibs);
            ```
        draft: false
        prerelease: false
