name: Release

on:
  #schedule:
    #- cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: release
      run: |
        .github/scripts/release.sh

    - name: git
      run: |
        git config user.name "qlibs@github.com"
        git config user.email "noreply@github.com"

    - name: commit
      run: |
        git add .
        git commit -m "Release $(date +'%Y_%m_%d')"

    - name: tag
      id: tag_name
      run: |
        TAG_NAME=$(date +'%Y_%m_%d')
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: push
      run: git push origin main

    - name: github
      uses: actions/create-release@v1
      with:
        tag_name: qlibs.${{ env.TAG_NAME }}
        release_name: qlibs.${{ env.TAG_NAME }}
        body: "Release: qlibs.${{ env.TAG_NAME }}"
        draft: false
        prerelease: false
