name: Release

on:
  #schedule:
    #- cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: release
      run: |
        .github/scripts/release.sh

    - name: git
      run: |
        git config user.name "qlibs@github.com"
        git config user.email "noreply@github.com"

    - name: commit
      run: |
        git add .
        git commit -m "Release $(date +'%Y_%m_%d')"

    - name: tag
      run: |
        TAG_NAME=$(date +'%Y_%m_%d')
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: push
      run: git push origin main

    - name: github
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        body: "Release - ${{ github.ref_name }}"
        draft: false
        prerelease: false
